include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**.g.dart"
    - "test/**"
    - "plugins/**"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    always_specify_types: false
    sort_constructors_first: false
    directives_ordering: false
    implementation_imports: false
    always_use_package_imports: false
    depend_on_referenced_packages: false
    avoid_classes_with_only_static_members: false
    avoid_positional_boolean_parameters: false