name: base_bloc_3
description: A new base project using bloc, Clean Architecture on Flutter 3.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #multi language
  easy_localization: ^3.0.1

  #state management
  flutter_bloc: ^8.0.1

  #dependency injection
  injectable: ^1.5.3
  get_it: ^7.2.0

  #serializable
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  dartz: ^0.10.1
  copy_with_extension: ^4.0.2
  equatable: ^2.0.3
  rxdart: ^0.27.5

  #networking
  retrofit: ^3.0.1+1
  dio: ^4.0.6
  connectivity_plus: ^2.3.4

  logger: ^1.1.0

  #local storage
  shared_preferences: ^2.0.15

  #routing
  auto_route: ^4.0.1

  #firebase
  firebase_core: ^1.24.0
  firebase_messaging: ^13.0.4

  flutter_local_notifications: ^11.0.1

  flutter_dotenv: ^5.0.2
  flutter_gen: ^4.3.0
  event_bus: ^2.0.0

  #view
  photo_view: ^0.14.0
  infinite_scroll_pagination: ^3.2.0
  top_snackbar_flutter: ^1.1.1
  flutter_svg: ^1.1.0
  shimmer: ^2.0.0

  #responsive
  flutter_screenutil: ^5.5.3+2
  device_preview: ^1.1.0
  cached_network_image: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  auto_route_generator: ^4.0.0
  copy_with_extension_gen: ^4.0.2
  flutter_gen_runner: ^4.3.0

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  assets:
    enable: true
    package_parameter_enabled: false

  font:
    enable: true


flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/env/
    - assets/images/
    - assets/svg/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/font/Lexend-Light.ttf
          weight: 300
        - asset: assets/font/Lexend-Regular.ttf
          weight: 400
        - asset: assets/font/Lexend-Medium.ttf
          weight: 500
        - asset: assets/font/Lexend-Bold.ttf
          weight: 700
